language: swift
xcode_project: fazendinha.xcodeproj
xcode_scheme: fazendinha_iOS
notifications:
  email: false
osx_image: xcode8.3

before_install:
  - brew unlink swiftlint
  - brew uninstall swiftlint
  - brew install swiftlint
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

script:
  - xcodebuild -scheme fazendinha_iOS -project fazendinha.xcodeproj -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3' -sdk iphonesimulator build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
